---

- hosts: controlplane
  tasks:

    - name: Get token from control plane
      shell: |
        kubeadm token create --print-join-command
      register: token
      become: False
    
  
- hosts: workernodes
  tasks:

    - name: Print token
      debug:
        msg : "{{ token }}"