---

- hosts: controlplane
  tasks:

    - name: Get token from control plane
      shell: |
        kubeadm token create --print-join-command
      register: token
      become: False
    
    - name: Set global variable
      set_fact:
        token_var : "{{ token }}"
          
  
- hosts: workernodes
  tasks:
  
    - name: Join workernodes to controlplane
      shell:
        "{{ hostvars['localhost']['token_var'].stdout }}"